name: Weekly Data Update

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas apify-client

      - name: Run update script
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
        run: python update_data.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # data 폴더 전체를 강제로 스테이징
          git add data/latest_monitoring.csv
          
          # 변경사항이 있든 없든(시간 컬럼 때문에 무조건 생김) 강제로 커밋
          git commit -m "Weekly Auto-Update: $(date)" || exit 0
          
          # 현재 브랜치로 강제 푸시
          git push origin main
